version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pro_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ******

  

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./pro:/app
    ports:
      - "8000:8000"
    depends_on:
      # - redis
      - db
    environment:
      - DATABASE_NAME=pro_1
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=*****
      - DATABASE_HOST=db
      - DATABASE_PORT=5432


   celery:
     build: .
     command: celery -A pro worker -l info
     volumes:
       - ./pro:/app  
     depends_on:
       - db
       - redis
       
   celery_beat:
     build: .
     command: celery -A pro beat -l info -S django
     volumes:
       - ./pro:/app  
     depends_on:
       - db
       - redis

   redis:
     image: "redis:latest"
     ports:
       - "6379:6379"


volumes:
  postgres_data:
