version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pro_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ahmed2000-

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./pro:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=pro_1
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Ahmed2000-
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6389
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  postgres_data: