# Generated by Django 5.0.8 on 2024-08-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('tz_id', models.CharField(max_length=255)),
                ('localtime_epoch', models.IntegerField()),
                ('localtime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('wind_kph', models.FloatField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('pressure_mb', models.FloatField()),
                ('cloud', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='current',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.DeleteModel(
            name='WeatherCurrent',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.DeleteModel(
            name='WeatherLocation',
        ),
    ]
