# Generated by Django 5.0.8 on 2024-08-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weatherdata_remove_weather_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='location_name',
            new_name='name',
        ),
    ]
