# Generated by Django 5.0.8 on 2024-08-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_weatherdata_localtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
